### ISSUE TITLE
Contract facade (?) and test (?)

### ISSUE THREAD

**Issue by Castau** [Runi-VN/CA-1#10]
See https://github.com/Runi-VN/CA-1/issues/9

**Comment by HrBjarup** [comment]
Our contract will be hardcoded so in my opinion we should drop the entity- and facade class for the contract.

**Comment by Castau** [comment]
Yes i thought that as well - the reason i left it as is until the meeting today, was so we could talk about what to do with this page, especially if we divide the work by milestone. I think there could be made something "more" out of this milestone to make it a little more interesting/challenging.
